/**
 * Lease Template Service
 * 
 * Handles generation of customized lease documents with system branding
 * Supports logo insertion, custom fields, and multiple formats
 */

import { isMockMode } from "@/mocks/mockManager";
import apiClient from "./apiClient";

const USE_MOCK = isMockMode();

/**
 * Generate customized lease document with system branding
 * @param {Object} options - Lease generation options
 * @param {string} options.leaseId - Base lease template ID
 * @param {Object} options.propertyData - Property information
 * @param {Object} options.landlordData - Landlord information
 * @param {Object} options.tenantData - Tenant information (optional)
 * @param {Object} options.customFields - Additional custom fields
 * @param {string} options.format - Output format (pdf, docx, doc)
 * @returns {Promise<Blob>} Generated lease document
 */
export const generateCustomizedLease = async ({
  leaseId,
  propertyData,
  landlordData,
  tenantData = null,
  customFields = {},
  format = "pdf",
}) => {
  if (USE_MOCK) {
    // In mock mode, return a mock PDF blob
    // In production, this would be generated server-side with logo and branding
    const mockPdfContent = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj
3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 <<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica-Bold
>>
>>
>>
endobj
4 0 obj
<<
/Length 200
>>
stream
BT
/F1 24 Tf
100 700 Td
(Rental Connects - Customized Lease Agreement) Tj
0 -30 Td
/F1 12 Tf
(Property: ${propertyData?.title || "N/A"}) Tj
0 -20 Td
(Landlord: ${landlordData?.full_name || "N/A"}) Tj
${tenantData ? `0 -20 Td\n(Tenant: ${tenantData.full_name || "N/A"}) Tj\n` : ""}
ET
endstream
endobj
xref
0 5
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000306 00000 n
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
506
%%EOF`;

    return new Blob([mockPdfContent], { type: "application/pdf" });
  }

  try {
    const { data } = await apiClient.post(
      `/leases/generate-customized/`,
      {
        lease_id: leaseId,
        property_data: propertyData,
        landlord_data: landlordData,
        tenant_data: tenantData,
        custom_fields: customFields,
        format,
      },
      {
        responseType: "blob",
      }
    );
    return data;
  } catch (err) {
    console.error("Generate customized lease error:", err);
    throw err.response?.data || { message: "Failed to generate customized lease" };
  }
};

/**
 * Preview customized lease (returns HTML preview)
 * @param {Object} options - Same as generateCustomizedLease
 * @returns {Promise<string>} HTML preview
 */
export const previewCustomizedLease = async (options) => {
  if (USE_MOCK) {
    return `
      <div style="font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto;">
        <div style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #0b6e4f; padding-bottom: 20px;">
          <img src="/Logo.png" alt="Rental Connects" style="max-width: 200px; margin-bottom: 10px;" />
          <h1 style="color: #0b6e4f; margin: 0;">Rental Connects</h1>
          <p style="color: #666; margin: 5px 0;">Lease Agreement</p>
        </div>
        <div style="margin-bottom: 30px;">
          <h2 style="color: #333; border-bottom: 1px solid #ddd; padding-bottom: 10px;">Property Information</h2>
          <p><strong>Property:</strong> ${options.propertyData?.title || "N/A"}</p>
          <p><strong>Address:</strong> ${options.propertyData?.address || "N/A"}</p>
          <p><strong>Rent:</strong> ${options.propertyData?.price ? `₵${options.propertyData.price}` : "N/A"}</p>
        </div>
        <div style="margin-bottom: 30px;">
          <h2 style="color: #333; border-bottom: 1px solid #ddd; padding-bottom: 10px;">Landlord Information</h2>
          <p><strong>Name:</strong> ${options.landlordData?.full_name || "N/A"}</p>
          <p><strong>Email:</strong> ${options.landlordData?.email || "N/A"}</p>
          <p><strong>Phone:</strong> ${options.landlordData?.phone || "N/A"}</p>
        </div>
        ${options.tenantData ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #333; border-bottom: 1px solid #ddd; padding-bottom: 10px;">Tenant Information</h2>
          <p><strong>Name:</strong> ${options.tenantData.full_name || "N/A"}</p>
          <p><strong>Email:</strong> ${options.tenantData.email || "N/A"}</p>
        </div>
        ` : ""}
        <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #0b6e4f; text-align: center; color: #666; font-size: 12px;">
          <p>This is a preview of your customized lease agreement.</p>
          <p>Generated by Rental Connects - ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
    `;
  }

  try {
    const { data } = await apiClient.post(`/leases/preview-customized/`, {
      lease_id: options.leaseId,
      property_data: options.propertyData,
      landlord_data: options.landlordData,
      tenant_data: options.tenantData,
      custom_fields: options.customFields,
    });
    return data.html_preview;
  } catch (err) {
    console.error("Preview customized lease error:", err);
    throw err.response?.data || { message: "Failed to preview customized lease" };
  }
};

export default {
  generateCustomizedLease,
  previewCustomizedLease,
};
